export const SET_CURRENT_SEARCH = 'SET_CURRENT_SEARCH';
export const SET_CURRENT_HASH = 'SET_CURRENT_HASH';
export const SEARCH_BY_HASH = 'SEARCH_BY_HASH';
export const SEARCH_BY_URL = 'SEARCH_BY_URL';
export const ADD_SEARCH_TO_HISTORY = 'ADD_SEARCH_TO_HISTORY';
export const REMOVE_SEARCH_FROM_HISTORY = 'REMOVE_SEARCH_FROM_HISTORY';
